import type { Ebook, EbookProvider } from "../types"

const CURATED: Ebook[] = [
  { id: "gutendex_1342",  title: "Pride and Prejudice",                author: "Austen, Jane",                           description: "A romantic novel of manners about Elizabeth Bennet.",                                                coverUrl: "https://covers.openlibrary.org/b/olid/OL66562M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/1342",  source: "curated", sourceName: "Project Gutenberg", category: "Classics",  pages: null },
  { id: "gutendex_2701",  title: "Moby Dick; Or, The Whale",           author: "Melville, Herman",                       description: "The narrative of Captain Ahab's obsession with a white whale.",                                        coverUrl: "https://covers.openlibrary.org/b/olid/OL23747W-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/2701",  source: "curated", sourceName: "Project Gutenberg", category: "Classics",  pages: null },
  { id: "gutendex_11",    title: "Alice's Adventures in Wonderland",    author: "Carroll, Lewis",                         description: "A young girl falls down a rabbit hole into a fantasy world.",                                           coverUrl: "https://covers.openlibrary.org/b/olid/OL18199782M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/11",  source: "curated", sourceName: "Project Gutenberg", category: "Fantasy",   pages: null },
  { id: "gutendex_84",    title: "Frankenstein; Or, The Modern Prometheus", author: "Shelley, Mary Wollstonecraft",      description: "A scientist creates a sentient creature in a Gothic novel.",                                            coverUrl: "https://covers.openlibrary.org/b/olid/OL450533M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/84",  source: "curated", sourceName: "Project Gutenberg", category: "Horror",     pages: null },
  { id: "gutendex_1661",  title: "The Adventures of Sherlock Holmes",  author: "Doyle, Arthur Conan",                    description: "A collection of twelve short stories featuring the detective.",                                         coverUrl: "https://covers.openlibrary.org/b/olid/OL259418W-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/1661",  source: "curated", sourceName: "Project Gutenberg", category: "Mystery",    pages: null },
  { id: "gutendex_158",   title: "Emma",                                author: "Austen, Jane",                           description: "A comedy of manners about the well-meaning but misguided Emma Woodhouse.",                               coverUrl: "https://covers.openlibrary.org/b/olid/OL24365367M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/158",  source: "curated", sourceName: "Project Gutenberg", category: "Classics",  pages: null },
  { id: "gutendex_768",   title: "Wuthering Heights",                   author: "Brontë, Emily",                          description: "A tale of passionate love and revenge on the Yorkshire moors.",                                        coverUrl: "https://covers.openlibrary.org/b/olid/OL17710929M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/768",  source: "curated", sourceName: "Project Gutenberg", category: "Romance",    pages: null },
  { id: "gutendex_1400",  title: "Great Expectations",                  author: "Dickens, Charles",                       description: "The story of Pip, an orphan, and his journey from humble beginnings to gentleman.",                      coverUrl: "https://covers.openlibrary.org/b/olid/OL18303667M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/1400",  source: "curated", sourceName: "Project Gutenberg", category: "Fiction",    pages: null },
  { id: "gutendex_4300",  title: "Ulysses",                             author: "Joyce, James",                           description: "A modernist novel chronicling a single day in Dublin.",                                                coverUrl: "https://covers.openlibrary.org/b/olid/OL498259M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/4300",  source: "curated", sourceName: "Project Gutenberg", category: "Fiction",    pages: null },
  { id: "gutendex_2554",  title: "Crime and Punishment",                author: "Dostoyevsky, Fyodor",                    description: "A young intellectual commits murder and struggles with guilt.",                                        coverUrl: "https://covers.openlibrary.org/b/olid/OL16986W-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/2554",  source: "curated", sourceName: "Project Gutenberg", category: "Fiction",    pages: null },
  { id: "gutendex_174",   title: "The Picture of Dorian Gray",          author: "Wilde, Oscar",                           description: "A man's portrait ages while he remains young in this Gothic novel.",                                    coverUrl: "https://covers.openlibrary.org/b/olid/OL247356W-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/174",  source: "curated", sourceName: "Project Gutenberg", category: "Horror",     pages: null },
  { id: "gutendex_1952",  title: "The Yellow Wallpaper",                author: "Gilman, Charlotte Perkins",              description: "A woman's descent into madness through a wallpaper pattern.",                                          coverUrl: null,  fileUrl: "https://www.gutenberg.org/ebooks/1952",  source: "curated", sourceName: "Project Gutenberg", category: "Horror",     pages: null },
  { id: "gutendex_1232",  title: "The Prince",                          author: "Machiavelli, Niccolò",                   description: "A political treatise on acquiring and maintaining power.",                                             coverUrl: "https://covers.openlibrary.org/b/olid/OL24161959M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/1232",  source: "curated", sourceName: "Project Gutenberg", category: "Philosophy", pages: null },
  { id: "gutendex_1497",  title: "The Republic",                        author: "Plato",                                  description: "A Socratic dialogue concerning justice and the ideal state.",                                           coverUrl: "https://covers.openlibrary.org/b/olid/OL25418587M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/1497",  source: "curated", sourceName: "Project Gutenberg", category: "Philosophy", pages: null },
  { id: "gutendex_344",   title: "The Odyssey",                         author: "Homer",                                  description: "The epic journey of Odysseus returning home after the Trojan War.",                                     coverUrl: "https://covers.openlibrary.org/b/olid/OL25422687M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/344",  source: "curated", sourceName: "Project Gutenberg", category: "Classics",  pages: null },
  { id: "gutendex_30254", title: "The War of the Worlds",               author: "Wells, H. G.",                           description: "An alien invasion of Earth from Mars.",                                                                coverUrl: "https://covers.openlibrary.org/b/olid/OL20256331M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/30254", source: "curated", sourceName: "Project Gutenberg", category: "Science Fiction", pages: null },
  { id: "gutendex_36",    title: "The Scarlet Letter",                  author: "Hawthorne, Nathaniel",                   description: "A tale of sin, guilt, and redemption in Puritan New England.",                                          coverUrl: "https://covers.openlibrary.org/b/olid/OL22204528M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/36",  source: "curated", sourceName: "Project Gutenberg", category: "Classics",  pages: null },
  { id: "gutendex_244",   title: "A Room with a View",                  author: "Forster, E. M.",                         description: "A young woman's journey of self-discovery in Edwardian England and Italy.",                              coverUrl: "https://covers.openlibrary.org/b/olid/OL6961122M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/2641", source: "curated", sourceName: "Project Gutenberg", category: "Romance",    pages: null },
  { id: "gutendex_74",    title: "The Adventures of Tom Sawyer",        author: "Twain, Mark",                            description: "A young boy's mischievous adventures along the Mississippi River.",                                     coverUrl: "https://covers.openlibrary.org/b/olid/OL6148393M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/74",  source: "curated", sourceName: "Project Gutenberg", category: "Children",   pages: null },
  { id: "gutendex_100",   title: "The Complete Works of William Shakespeare", author: "Shakespeare, William",              description: "All 37 plays, 154 sonnets, and 4 narrative poems.",                                                    coverUrl: "https://covers.openlibrary.org/b/olid/OL25438778M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/100", source: "curated", sourceName: "Project Gutenberg", category: "Drama",      pages: null },
  { id: "gutendex_1998",  title: "Thus Spoke Zarathustra",              author: "Nietzsche, Friedrich",                   description: "A philosophical novel about the Übermensch and eternal recurrence.",                                    coverUrl: "https://covers.openlibrary.org/b/olid/OL15201079M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/1998", source: "curated", sourceName: "Project Gutenberg", category: "Philosophy", pages: null },
  { id: "gutendex_46",    title: "A Christmas Carol in Prose",          author: "Dickens, Charles",                       description: "A miserly old man is visited by three ghosts on Christmas Eve.",                                        coverUrl: "https://covers.openlibrary.org/b/olid/OL18303607M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/46",  source: "curated", sourceName: "Project Gutenberg", category: "Fiction",    pages: null },
  { id: "gutendex_8800",  title: "The Divine Comedy",                   author: "Alighieri, Dante",                       description: "The epic poem of Dante's journey through Hell, Purgatory, and Paradise.",                               coverUrl: "https://covers.openlibrary.org/b/olid/OL24219862M-L.jpg",  fileUrl: "https://www.gutenberg.org/ebooks/8800", source: "curated", sourceName: "Project Gutenberg", category: "Poetry",     pages: null },
  { id: "gutendex_1080",  title: "A Modest Proposal",                   author: "Swift, Jonathan",                        description: "A satirical essay suggesting impoverished Irish sell their children as food.",                           coverUrl: null,  fileUrl: "https://www.gutenberg.org/ebooks/1080", source: "curated", sourceName: "Project Gutenberg", category: "Fiction",    pages: null },
]

export class CuratedProvider implements EbookProvider {
  readonly name = "curated"
  readonly sourceName = "Classic Library"

  async searchEbooks(query?: string, options?: { category?: string; limit?: number }): Promise<Ebook[]> {
    let results = CURATED

    if (query) {
      const q = query.toLowerCase()
      results = results.filter(
        (b) => b.title.toLowerCase().includes(q) || b.author.toLowerCase().includes(q)
      )
    }

    if (options?.category) {
      const cat = options.category.toLowerCase()
      results = results.filter((b) => b.category?.toLowerCase() === cat)
    }

    const limit = options?.limit || 24
    return results.slice(0, limit)
  }

  async getEbook(id: string): Promise<Ebook | null> {
    return CURATED.find((b) => b.id === id) || null
  }
}
